trunk/commando/board/urls.py
from django.conf.urls import patterns, include, url

from board import views

urlpatterns = patterns('',
    url(r'^$', views.view_index, name='index'),
    url(r'^(?P<board_id>\d+)/$', views.view_board, name='board'),
    url(r'^(?P<board_id>\d+)/move/$', views.view_make_move, name='move'),
    url(r'^login/$', views.view_login, name='login'),
    url(r'^register/$', views.view_register, name='register'),
    url(r'^logout/$', views.view_logout, name='logout'),
    url(r'^newgame/$', views.view_newgame, name='newgame'),
    url(r'^(?P<board_id>\d+)/abandon/$', views.view_abandon, name='abandon'),
)

trunk/commando/commando/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^board/', include('board.urls', namespace="board")),
    url(r'^admin/', include(admin.site.urls)),
)

trunk/commando/board/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

class Color:
    ORANGE = 1
    BLUE = 2
    
    CHOICES = (
        (ORANGE, 'Orange'),
        (BLUE, 'Blue')
    )
    
    @staticmethod
    def get_opposite(color):
        if color == Color.ORANGE:
            return Color.BLUE
        if color == Color.BLUE:
            return Color.ORANGE
        raise Exception('Invalid color')
        
class Board(models.Model):
    #width = models.IntegerField()
    #height = models.IntegerField()
    color_to_move = models.IntegerField(choices=Color.CHOICES, default=Color.ORANGE)
    player_orange = models.ForeignKey(User, related_name='boards_orange')
    player_blue = models.ForeignKey(User, related_name='boards_blue')
    
    def __unicode__(self):
        return 'Board#' + str(self.id) + ':[' + self.player_orange.username + ' vs ' + self.player_blue.username + ']'
        
    def has_pieces_at(self, x, y):
        return len(self.get_pieces_at(x, y)) > 0
        
    def get_pieces_at(self, x, y):
        return Piece.objects.filter(board=self.pk, x=x, y=y)
        
    def get_pieces(self):
        return Piece.objects.filter(board=self.pk)
        
    def count_pieces_of_color_at(self, x, y, color):
        return len(Piece.objects.filter(board=self.pk, x=x, y=y, color=color))
        
    def is_piece_of_color_at(self, x, y, color):
        return self.count_pieces_of_color_at(x, y, color) > 0
        
    def get_piece_of_color_at(self, x, y, color):
        pieces = Piece.objects.filter(board=self.pk, x=x, y=y, color=color)
        if len(pieces) > 0:
            return pieces[0]
        return None
        
    def get_width(self):
        return 12
    def get_height(self):
        return 12
    def contains_position(self, x, y):
        return x >= 0 and y >= 0 and x < self.get_width() and y < self.get_width()
    
    def try_move_to(self, user, from_x, from_y, to_x, to_y):
        if not self.is_player_to_move(user):
            return (False, "It's not your turn to move.")
        pieces = self.get_pieces_at(from_x, from_y)
        if len(pieces) == 0:
            return (False, 'No piece selected.')
        return pieces[0].try_move_to(to_x, to_y)
        
    def is_player_to_move(self, user):
        return user == self.get_player_to_move()
        
    def get_player_to_move(self):
        if self.color_to_move == Color.ORANGE:
            return self.player_orange
        if self.color_to_move == Color.BLUE:
            return self.player_blue
        raise Exception('Invalid color to move')
        
    def populate_and_save(self):
        def make_piece_at(x, y, piece_type, color):
            piece = Piece()
            piece.x = x
            piece.y = y
            piece.piece_type = piece_type
            piece.color = color
            piece.board = self
            piece.save()
        
        self.save()
        
        make_piece_at(1, 4, Piece.NORMAL, Color.ORANGE)
        make_piece_at(2, 4, Piece.OFFENSE, Color.ORANGE)
        make_piece_at(3, 4, Piece.DEFENSE, Color.ORANGE)
        
        make_piece_at(5, 4, Piece.NORMAL, Color.ORANGE)
        make_piece_at(6, 4, Piece.NORMAL, Color.ORANGE)
        
        make_piece_at(8, 4, Piece.OFFENSE, Color.ORANGE)
        make_piece_at(9, 4, Piece.DEFENSE, Color.ORANGE)
        make_piece_at(10, 4, Piece.NORMAL, Color.ORANGE)
        
        make_piece_at(4, 2, Piece.NORMAL, Color.ORANGE)
        make_piece_at(5, 2, Piece.DEFENSE, Color.ORANGE)
        make_piece_at(6, 2, Piece.DEFENSE, Color.ORANGE)
        make_piece_at(7, 2, Piece.NORMAL, Color.ORANGE)
        
        
        make_piece_at(1, 7, Piece.NORMAL, Color.BLUE)
        make_piece_at(2, 7, Piece.DEFENSE, Color.BLUE) # heavy should be opposite cavalry
        make_piece_at(3, 7, Piece.OFFENSE, Color.BLUE)
        
        make_piece_at(5, 7, Piece.NORMAL, Color.BLUE)
        make_piece_at(6, 7, Piece.NORMAL, Color.BLUE)
        
        make_piece_at(8, 7, Piece.DEFENSE, Color.BLUE)
        make_piece_at(9, 7, Piece.OFFENSE, Color.BLUE)
        make_piece_at(10, 7, Piece.NORMAL, Color.BLUE)
        
        make_piece_at(4, 9, Piece.NORMAL, Color.BLUE)
        make_piece_at(5, 9, Piece.DEFENSE, Color.BLUE)
        make_piece_at(6, 9, Piece.DEFENSE, Color.BLUE)
        make_piece_at(7, 9, Piece.NORMAL, Color.BLUE)
        

        
adjacent_deltas = [(0, 1), (1, 0), (0, -1), (-1, 0)]
def get_adjacent_positions(x, y):
    return [(a[0] + int(x), a[1] + int(y)) for a in adjacent_deltas]

class Piece(models.Model):
    NORMAL = 1
    DEFENSE = 2
    OFFENSE = 3
    
    board = models.ForeignKey(Board)
    piece_type = models.IntegerField(choices=(
        (NORMAL, 'Light Infantry'),
        (DEFENSE, 'Heavy Infantry'),
        (OFFENSE, 'Cavalry')
    ))
    x = models.IntegerField()
    y = models.IntegerField()
    color = models.IntegerField(choices=Color.CHOICES)
    
    
    def __unicode__(self):
        #return self.get_type_name()
        return self.get_piece_type_display()
        
    #def get_type_name(self):
    #    return PieceType.get_name(self.piece_type)
        
    def count_adjacent_enemies(self):
        return sum([
            (1 if self.board.is_piece_of_color_at(a[0], a[1], Color.get_opposite(self.color)) else 0)
            for a in self.get_adjacent_positions()
        ])
    def get_adjacent_enemies(self):
        #return [self.board.get_piece_of_color_at(a[0], a[1], Color.get_opposite(self.color)) for a in self.get_adjacent_positions()]
        result = []
        for position in self.get_adjacent_positions():
            other = self.board.get_piece_of_color_at(position[0], position[1], Color.get_opposite(self.color))
            if other:
                result.append(other)
        return result
        
    def get_adjacent_positions(self):
        return get_adjacent_positions(self.x, self.y)
        
    def get_move_legality(self, dest_x, dest_y):
        dest_x = int(dest_x)
        dest_y = int(dest_y)
        
        if not self.board.contains_position(dest_x, dest_y):
            return (False, "Can't move off the board, you doofus.")
        if self.board.color_to_move != self.color:
            return (False, "It's not that player's turn to move.")
        if dest_x == self.x and dest_y == self.y:
            return (False, "Can't move in place.")
        if self.count_adjacent_enemies() > 0:
            return (False, 'That piece is engaged and cannot move because it is adjacent to the enemy.')
        if not ((dest_x, dest_y) in self.get_adjacent_positions()):
            return (False, 'Can only move to adjacent squares. (No diagonals.)')
        if self.board.has_pieces_at(dest_x, dest_y):
            return (False, "Can't move onto another piece.")
        return (True, None)
        
    def try_move_to(self, dest_x, dest_y):
        legal, fail_reason = self.get_move_legality(dest_x, dest_y)
        if not legal:
            return (legal, fail_reason)
            
        self.x = dest_x
        self.y = dest_y
        self.save()
        
        # only check adjacent enemies for possible kills because pieces don't kill themselves by walking into kill squares
        for enemy in self.get_adjacent_enemies():
            if enemy.get_current_pressure_sustained() >= enemy.get_pressure_to_kill():
                enemy.delete()
        
        if self.board.color_to_move == Color.ORANGE:
            self.board.color_to_move = Color.BLUE
        else:
            self.board.color_to_move = Color.ORANGE
        self.board.save()
        return (True, None)
        
    def get_pressure_exerted(self):
        if self.piece_type == Piece.OFFENSE:
            return 2
        else:
            return 1
            
    def get_current_pressure_sustained(self):
        result = 0
        for enemy in self.get_adjacent_enemies():
            result += enemy.get_pressure_exerted()
        return result
        
    def get_pressure_to_kill(self):
        if self.piece_type == Piece.DEFENSE:
            return 3
        else:
            return 2
        

trunk/commando/board/views.py
import random

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from board.models import Board, Piece, Color

def view_abandon(request, board_id): ####################################### TODO: don't abandon a game that isn't yours
    if not request.user.is_authenticated():
        # usually only if session expires
        messages.error(request, 'Please log in.')
        return redirect('board:index')
        
    if request.method != 'POST':
        return redirect('board:index')
        
    board = Board.objects.get(id=board_id)
    board.delete()
    
    messages.success(request, 'Game ended successfully.')
    return redirect('board:index')
    
def view_newgame(request):
    if not request.user.is_authenticated():
        # usually only if session expires
        messages.error(request, 'Please log in.')
        return redirect('board:index')
        
    if request.method != 'POST':
        return redirect('board:index')
        
    opponents = User.objects.filter(username=request.POST['opponent_username'])
    if len(opponents) == 0:
        messages.error(request, 'No such user.')
        return redirect('board:index')
    opponent = opponents[0]
        
    board = Board()
    selected_color = request.POST['my_color']
    if selected_color == 'orange':
        board.player_orange = request.user
        board.player_blue = opponent
    elif selected_color == 'blue':
        board.player_orange = opponent
        board.player_blue = request.user
    elif selected_color == 'random':
        if random.random() < .5:
            board.player_orange = request.user
            board.player_blue = opponent
        else:
            board.player_orange = opponent
            board.player_blue = request.user
    else:
        messages.error(request, 'Select a color to play as.')
        return redirect('board:index')
            
    board.populate_and_save()

    return redirect('board:board', board.id)
        
def view_logout(request):
    if request.method == 'POST': # Is this necessary? Might be possible to grief users by logging them out from off-site.
        logout(request)
    return redirect('board:index')
    
def view_login(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                #messages.success(request, 'Logged in.') # already obvious from index page
            else:
                messages.error(request, 'That account is disabled.')
        else:
            messages.error(request, 'Invalid username/password combination.')
            
    return redirect('board:index')
    
def view_register(request):
    if request.method == 'POST':
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        
        if password1 != password2:
            messages.error(request, "The given passwords don't match.")
        else:
            user = User.objects.create_user(request.POST['username'], None, password1)
            login(request, user)
            messages.success(request, 'Account created successfully.')
    
    return redirect('board:index')
        
def view_index(request):
    username = None
    if request.user.is_authenticated():
        username = request.user.username

    return render(request, 'board/index.html', { 'username':username, 'board_list':Board.objects.all() })
        
def view_make_move(request, board_id):
    if request.method == 'POST':
        board = get_object_or_404(Board, pk=board_id)
        from_x = request.POST['from_x']
        from_y = request.POST['from_y']
        to_x = request.POST['to_x']
        to_y = request.POST['to_y']
        
        success, fail_reason = board.try_move_to(request.user, from_x, from_y, to_x, to_y)
        if not success:
            messages.error(request, fail_reason)
        return redirect('board:board', board_id)
    else:
        # sometimes happens when recovering from an error
        return redirect('board:board', board_id)
        
def view_board(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    
    rows = []
    for y in range(0, board.get_height()):
        rows.append([])
        for x in range(0, board.get_width()):
            pieces = board.get_pieces_at(x, y)
            if len(pieces) == 0:
                rows[y].append(None)
            else:
                piece = pieces[0]
                if piece.color == Color.ORANGE:
                    color = 'orange'
                elif piece.color == Color.BLUE:
                    color = 'blue'
                else:
                    raise Exception('Invalid piece owner')
                    
                #if board.color_to_move == Color.ORANGE:
                #    to_move = 'Orange to move.'
                #elif board.color_to_move == Color.BLUE:
                #    to_move = 'Blue to move.'
                #else:
                #    raise Exception('Invalid color to move')
                if board.is_player_to_move(request.user):
                    to_move = 'YOUR MOVE'
                else:
                    to_move = board.get_player_to_move().username + ' to move.'
                    
                if piece.piece_type == Piece.NORMAL:
                    rows[y].append('board/images/' + color + '-light.png')
                elif piece.piece_type == Piece.DEFENSE:
                    rows[y].append('board/images/' + color + '-heavy.png')
                elif piece.piece_type == Piece.OFFENSE:
                    rows[y].append('board/images/' + color + '-cavalry.png')
                else:
                    raise Exception('Invalid piece type')
                    
    return render(request, 'board/board.html', { 'rows':rows, 'to_move':to_move, 'board':board })
    

trunk/commando/board/templates/board/board.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'board/style.css' %}" />

<center>

<p><big>{{ to_move }}</big></p>

{% if messages %}
    {% for message in messages %}
		<p>{{ message }}</p>
    {% endfor %}
{% endif %}


<form id="abandon_form" method="post" action="{% url 'board:abandon' board.id %}">
	{% csrf_token %}
	<input type="button" value="Abandon Game" id='abandon_button'>
</form>
<script>
	var abandon_form = document.getElementById('abandon_form')
	var abandon_button = document.getElementById('abandon_button')
	abandon_button.addEventListener('click', function() {
		if(confirm("Abandoning the game cannot be undone and prevents you from returning to it later. Are you sure?")) {
			abandon_form.submit()
		}
	})
</script>




<script>
	var idToSelectable = {}
</script>

<table border=1>
{% for row in rows %}
	<tr>
	{% for square in row %}
		<td>
		{% with square_counter=forloop.counter0|stringformat:"s" row_counter=forloop.parentloop.counter0|stringformat:"s" %}
			{% with id=square_counter|add:","|add:row_counter %}
				
				{% if square %}
					<img src="{% static square %}" width="45" height="45" id="{{ id }}">
					<script> idToSelectable['{{ id }}'] = true </script>
				{% else %}
					<div style="width:45px; height:45px;" id="{{ id }}"></div>
				{% endif %}
				
			{% endwith %}
		{% endwith %}
		</td>
	{% endfor %}
	</tr>
{% endfor %}
</table>

</center>

<form id="move" method="post" action="{% url 'board:move' board.id %}">
	{% csrf_token %}
	<input type="hidden" name="from_x" id="from_x"/>
	<input type="hidden" name="from_y" id="from_y"/>
	<input type="hidden" name="to_x" id="to_x"/>
	<input type="hidden" name="to_y" id="to_y"/>
</form>

<script>
	var selectedId = undefined

	for(var x = 0; x < 12; x += 1)
		for(var y = 0; y < 12; y += 1)
			(function(x, y) {
				var objId = x + ',' + y
				var obj = document.getElementById(objId)
				obj.addEventListener('click', function() {
					if(selectedId) { // already has selection
						if(selectedId === objId) { // clicked same square
							obj.className = ''
							selectedId = undefined
						}
						else { // move
							document.getElementById('to_x').value = x
							document.getElementById('to_y').value = y
							//document.forms[0].submit()
							document.getElementById('move').submit()
						}
					}
					else { // picking piece
						if(idToSelectable[objId]) { // selectable piece
							obj.className = 'selected_piece'
							selectedId = objId
							document.getElementById('from_x').value = x
							document.getElementById('from_y').value = y
						}
						// else ignore this input
					}
				})
			})(x, y)
</script>

trunk/commando/board/templates/board/index.html
{% if messages %}
    {% for message in messages %}
		<p>{{ message }}</p>
    {% endfor %}
{% endif %}

{% if username %}
	<form id="logout" method="post" action="{% url 'board:logout' %}">
		{% csrf_token %}
		<span>Logged in as {{ username }}.</span> <input type="submit" value="Log Out">
	</form>
	
	{% if board_list %}
		<p>Games in progress:</p>
		<ul>
		{% for board in board_list %}
			<li><a href="{% url 'board:board' board.id %}">{{ board }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No games currently in progress.</p>
		
		<form id="newgame" method="post" action="{% url 'board:newgame' %}">
			{% csrf_token %}
			<fieldset>
				<legend>Start a new game</legend>
				<label>Against whom?</label> <input type="text" name="opponent_username" placeholder="username"> <br>
				<label>I play as:</label><br>
					<label for="radio-orange">Orange</label>
					<input type="radio" id="radio-orange" name="my_color" value="orange"> <br>
					
					<label for="radio-blue">Blue</label>
					<input type="radio" id="radio-blue" name="my_color" value="blue"> <br>
					
					<label for="radio-random">Random</label>
					<input type="radio" id="radio-random" name="my_color" value="random"> <br>
				<input type="submit" value="Play">
				
				<p style="font-size:smaller;">Ugliest UI ever.</p>
			</fieldset>
		</form>
		
	{% endif %}
{% else %}
	<form id="login" method="post" action="{% url 'board:login' %}">
		{% csrf_token %}
		<fieldset>
			<legend>Log in to play!</legend>
			<label>Username:</label> <input type="text" name="username" placeholder="username"> <br>
			<label>Password:</label> <input type="password" name="password" placeholder="omg"> <br>
			<input type="submit" value="Log In">
		</fieldset>
	</form>
	
	<form id="register" method="post" action="{% url 'board:register' %}">
		{% csrf_token %}
		<fieldset>
			<legend>Don't have an account? Make one now. It's fast and easy!</legend>
			<label>Username:</label> <input type="text" name="username" placeholder="username"> <br>
			<label>Password:</label> <input type="password" name="password1" placeholder="password"> <br>
			<label>Password (again):</label> <input type="password" name="password2" placeholder="password"> <br>
			<input type="submit" value="Register">
		</fieldset>
	</form>
{% endif %}